  version: '2'
  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:7.4.4
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 22181:2181

    kafka:
      image: confluentinc/cp-kafka:7.4.4
      depends_on:
        - zookeeper
      ports:
        - 29095:29095
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29095
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      ports:
        - 8989:8080
      environment:
        KAFKA_CLUSTERS_0_NAME: kafka
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092 # Include all Kafka nodes in bootstrap servers list
        KAFKA_CLUSTERS_0_METRICS_PORT: 9997 # Assuming JMX metrics port of the first Kafka node for simplicity
      depends_on:
        - kafka